#Placing a Hopper under the composter, it will fill extraloot loot into the hopper

Hopperinteraction: true

#Here you can define extra compost to be composted, like stone if you wish.
#Also note !! That you can only take level from 1 to 7, (use Integer and !no! decimal numbers like 0.5)

Text:
  Compost_Gui: "wooden_shovel"
  CompostGui_Text: "Here is a list of compostable goods"
  Loot_Gui: "BOOK"
  LootGui_Text: "Here is a list of lootable things"
  ReloadMessage: "reloaded"
