name: ComposterPlus
author: Ninoo
version: 1.4
api-version: 1.16
main: main.java.net.fruchtlabor.composterplus.ComposterPlus
soft-depend: [Vault]
commands:
  cp:
    description: "Main command"
    usage:
